[package]
name = "rust-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.31.0"
sscanf = "*"
rusttype = { version = "*", features = ["gpu_cache"] }
image = "*"
rodio = "*"